name: KevsPermissions
version: 2.0
author: KevSlashNull
main: kevslashnull.permissions.PermissionsPlugin
description: Maintain your server permissions now - performant and lightweight!
commands:
  kp:
    aliases: []